"""initial

Revision ID: 01adaa1f3a79
Revises: 
Create Date: 2021-06-02 12:42:48.270202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01adaa1f3a79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divvy',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('stoptime', sa.DateTime(), nullable=True),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_name', sa.String(length=45), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(length=45), nullable=True),
    sa.Column('usertype', sa.String(length=45), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divvy')
    # ### end Alembic commands ###
